### ISSUE TITLE
Classes are getting generated in the sass version

### ISSUE THREAD

**Issue by ZeeCoder** [sprity/sprity-sass#3]
Title says it all: classes are getting generated with the normal and retina background-images + media queries in the sass file.

Also: using the "prefix" option does nothing opposed to when generating vanilla css.

**Comment by ZeeCoder** [comment]
Also: there's no function which could be used to get the image backgrounds.
Instead, only the classes are available. O.o

**Comment by ZeeCoder** [comment]
@aslansky ?

**Comment by aslansky** [comment]
Thats how this style processors works right now. If you need it in a different way you could either use your own template or create a new processor or (even better) generate a pull request. If you decide to create a pull request please keep in mind that it should stay backwards compatible. So you would need to introduce a new option for your desired behaviour.

With the prefix I am not sure what you mean. Using the prefix option generates (at least for me): 

```
.TEST {
  background-image: url("dist/icons.png");
}
@media (-webkit-min-device-pixel-ratio: 2),
(min-resolution: 192dpi) {
  .TEST {
    background-image: url("dist/icons@2x.png");
    background-size: 149px 133px;
  }
}
@media (-webkit-min-device-pixel-ratio: 3),
(min-resolution: 384dpi) {
  .TEST {
    background-image: url("dist/icons@3x.png");
    background-size: 149px 133px;
  }
}
```

I can have a look into it. But I need more information (gulp/grunt task or the command you used).

**Comment by ZeeCoder** [comment]
I had some time on my hands, so I checked again.

Interestingly now I don't have problems with the prefixes either, even though I clearly remember having an issue with it.
Sadly I left the gulp task in such a state that doesn't reproduce the error, and since it was quite long ago, I can't remember how exactly it looked like before.

I think I just couldn't figure out how to configure the task properly, I remember struggling with the meanings of "name", "prefix", "style", even after reading the comments.
Somehow the labels just didn't click with my brain, it wasn't intuitive enough for me. :/

Anyway, I installed the cli, and after playing around with it a bit, I could easily change 2 parts of the task, and now it seems to work. :)

For the record though, here are the old and the new tasks:
_(I changed the "dimension", "style" and "prefix" options.)_

### Old

``` js
gulp.task('sprites', function () {
    var sprity = require('sprity');

    var imagesTargetPath = util.dest(util.imagesDestDir + '/' + util.spriteImagesDestDir);
    var stylesTargetPath = util.src('styles/' + util.spriteStylesSrcDir);
    var spriteStyleName = '_sprites';

    del.sync(imagesTargetPath);
    del.sync(stylesTargetPath + '/' + spriteStyleName + '.scss');

    return sprity
        .src({
            src: util.src(util.spriteImagesSrcDir + '/**/*.png'),
            // src: util.src(util.spriteImagesSrcDir + '/**/*.png'),
            split: true,
            processor: 'sass',
            name: 's', // The prefix used for the images
            // name: 's-icons', // If `split` is not true
            dimension: [{
                ratio: 1
            }, {
                ratio: 2
            }],
            style: spriteStyleName // The generated style's name
            // prefix: 's' // The prefix given for the generated css classes
        })
        .pipe($.if('*.png',
            gulp.dest(imagesTargetPath),
            gulp.dest(stylesTargetPath)
        ));
});
```

### New

``` js
gulp.task('sprites', function () {
    var sprity = require('sprity');

    var imagesTargetPath = util.dest(util.imagesDestDir + '/' + util.spriteImagesDestDir);
    var stylesTargetPath = util.src('styles/' + util.spriteStylesSrcDir);
    var spriteStyleName = '_sprites';

    del.sync(imagesTargetPath);
    del.sync(stylesTargetPath + '/' + spriteStyleName + '.scss');

    return sprity
        .src({
            src: util.src(util.spriteImagesSrcDir + '/**/*.png'),
            // src: util.src(util.spriteImagesSrcDir + '/**/*.png'),
            split: true,
            processor: 'sass',
            name: 's', // The prefix used for the images
            dimension: [{
                ratio: 1, dpi: 72
            }, {
                ratio: 2, dpi: 192
            }],
            style: './' + spriteStyleName + '.scss', // The generated style's name
            prefix: 's' // The prefix given for the generated css classes
        })
        .pipe($.if('*.png',
            gulp.dest(imagesTargetPath),
            gulp.dest(stylesTargetPath)
        ));
});
```

About the background images: I would create a PR, but I think I would struggle way too much for way too little with my skills. :)

Thanks for the reaction btw, and sorry for the inconvenience. :)
